INSERT INTO topics (key, name, sort_order) VALUES
('FREE UPSKILL PROGRAMS', 'Free Upskill Programs', 0),
('STANDARD TRAINING', 'Standard Foundational Training', 1),
('EA  PA TRAINING-OUTSOURCED MANP', 'EA / PA Training - Outsourced Manpower', 2),
('REVISED EA PA TRAINING', 'Revised EA PA Training', 3),
('CM TRAINING', 'CM Training', 4),
('REVISED CM TRAINING', 'Revised CM Training', 5),
('CALENDAR MANAGEMENT TRAINING', 'Calendar Management Training', 6),
('BUSINESS LAW', 'Business Law', 7),
('ESTATE PLANNING', 'Estate Planning', 8),
('FAMILY LAW', 'Family Law', 9),
('HEALTH SUBRO', 'Health Subro', 10),
('IMMIGRATION LAW', 'Immigration Law', 11),
('INTELLECTUAL PROPERTY LAW', 'Intellectual Property Law', 12),
('LIEN VERIFICATION', 'Lien Verification', 13),
('LITIGATION', 'Litigation', 14),
('MASS TORT', 'Mass Tort', 15),
('MEDSUM AND DEMAND', 'Medsum and Demand', 16),
('PROPERTY DAMAGE', 'Property Damage Claims Training', 17),
('REAL ESTATE LAW', 'Real Estate Law', 18),
('HANDOUTS', 'Handouts', 19),
('TRAINING TOOLS AND RESOURCES', 'Training Tools and Resources', 20),
('OTHER RESOURCES', 'Other Resources', 21);
