name = "case-management-training"
compatibility_date = "2024-03-20"
pages_build_output_dir = "./" 

[[d1_databases]]
binding = "DB" 
database_name = "lshcasemanagementtraining-trainingcrmlogins"
database_id = "9b1afc1b-a26f-4fc2-aadf-acb9e704b75f"
